services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql_server
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "MyStr0ngP@ssword"
      ACCEPT_EULA: "Y"
    volumes:
      - mssql_data:/var/opt/mssql
    restart: unless-stopped

  mssql-init:
    image: mcr.microsoft.com/mssql/server:2022-latest
    depends_on:
      - mssql
    entrypoint: >
      bash -c "
        sleep 20 &&
        /opt/mssql-tools18/bin/sqlcmd -S mssql -U SA -P 'MyStr0ngP@ssword' -No -i /init-db.sql
      "
    volumes:
      - ./init-db.sql:/init-db.sql
    restart: "no"

volumes:
  mssql_data: