services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql_server
    ports:
      - "${DB_PORT}:${DB_PORT}"
    environment:
      SA_PASSWORD: ${DB_PASSWORD}
      ACCEPT_EULA: "Y"
    volumes:
      - mssql_data:/var/opt/mssql
    restart: unless-stopped

  mssql-init:
    image: mcr.microsoft.com/mssql/server:2022-latest
    depends_on:
      - mssql
    entrypoint: >
      bash -c "
        sleep 20 &&
        /opt/mssql-tools18/bin/sqlcmd -S mssql -U SA -P '${DB_PASSWORD}' -No -i /init-db.sql
      "
    volumes:
      - ./init-db.sql:/init-db.sql
    restart: "no"

  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: moex_candle_timer
    depends_on:
      - mssql-init
    environment:
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_SERVER=mssql
      - DB_NAME=${DB_NAME}
      - DB_PORT=${DB_PORT}
      - SECURITY=${SECURITY}
      - ENGINE=${ENGINE}
      - MARKET=${MARKET}
    volumes:
      - ./app:/app
      - /app/node_modules
    restart: unless-stopped

volumes:
  mssql_data: